version: "3.9"

services:
  php_7_1:
    image: php:$PHP_TAG_7_1
    pull_policy: missing
    container_name: "${PROJECT_NAME}_php_7_1"
## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_XDEBUG_MODE: profile
#      PHP_XDEBUG_USE_COMPRESSION: false
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/php/local#docker-for-mac
#    - backend:/var/www/html
## For XHProf and Xdebug profiler traces
#    - files:/mnt/files

  php_7_2:
    image: wodby/php:$PHP_TAG_7_2
    pull_policy: missing
    container_name: "${PROJECT_NAME}_php_7_2"
    volumes:
    - ./:/var/www/html:cached

  php_7_4:
    image: wodby/php:$PHP_TAG_7_4
    pull_policy: missing
    container_name: "${PROJECT_NAME}_php_7_4"
    volumes:
    - ./:/var/www/html:cached

  php_8_0:
    image: wodby/php:$PHP_TAG_8_0
    pull_policy: missing
    container_name: "${PROJECT_NAME}_php_8_0"
    volumes:
    - ./:/var/www/html:cached

#x-mutagen:
#  sync:
#    defaults:
#      ignore:
#        vcs: true
#        paths:
#        - .DS_Store
#        - .history
#        - .idea
#    backend:
#      alpha: "."
#      beta: "volume://backend"
#      configurationBeta:
#        permissions:
#          defaultFileMode: 0644
#          defaultDirectoryMode: 0755
#          defaultOwner: "id:501"
#          defaultGroup: "id:20"

#volumes:
## Mutagen for macOS users
#  backend:
## For Xdebug profiler
#  files:
